spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee_management_system
    username: root
    password: mysqladmin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
